@extends('layouts.app')

@section('content')
<div style="margin-right: auto; margin-left: auto; max-width: 1180px; width: 100%;">
    <h1 style="margin-bottom: 40px; text-align: center;">
        <span>
            ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ ОБ  ИСПОЛЬЗОВАНИИ <span style="display: inline-block;">МОБИЛЬНОГО ПРИЛОЖЕНИЯ</span> «Hitfly»
        </span>
    </h1>
    <span style="padding-left: 15px; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 0; padding-top: 0; padding-right: 0; padding-bottom: 0;">
        <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1. </span>Настоящее Пользовательское соглашение (далее: Соглашение) устанавливает условия использования Мобильного приложения «Hitfly» (далее: Hitfly) для Устройств и подлежит заключению между администрацией Hitfly и Пользователем.</span>
        <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2. </span>Применимое право: действующее законодательство Российской Федерации. Условия Соглашения являются публичной офертой в соответствии с частью 2 ст. 437 Гражданского кодекса Российской Федерации. Использование Hitfly возможно исключительно на условиях Соглашения.</span>
        <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3. </span>Использование Hitfly является акцептом публичной оферты и подтверждением согласия Пользователя с условиями Соглашения. В случае несогласия Пользователя с условиями Соглашения использование Приложения должно быть немедленно прекращено.</span>
        <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4. </span>Настоящее Соглашение может быть изменено и/или дополнено Администрацией в одностороннем порядке. При этом продолжение использования Hitfly после внесения изменений и/или дополнений в настоящее Соглашение, означает согласие Пользователя с такими изменениями и/или дополнениями.</span>
        <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5. </span>Обращения, предложения и претензии Пользователей к Администрации, связанные с содержанием, функционированием Hitfly, нарушением прав и интересов третьих лиц, требований законодательства Российской Федерации, а также для запросов уполномоченных законодательством Российской Федерации лиц могут быть направлены на адрес электронной почты: info@myhitfly.ru. Язык обращений: русский.</span>
    </span>
    <div>
        <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 0; padding-top: 0; padding-right: 0; padding-bottom: 0;">
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">1. </span>Для целей настоящего соглашения даны определения следующим терминам:</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.1 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Администрация Hitfly</span> (далее: Администрация) – юридическое лицо, Индивидуальный Предприниматель Турок Александр Николаевич, ИНН 771772607892, ОГРНИП 314774621100334, юридический адрес: 129515, г. Москва, улица Академика Королева, дом 4 корпус 2, квартира 472.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.2 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Мобильное приложение Hitfly</span> – мобильное приложение, разработанное для мобильных операционных систем iOS и Android, с целью размещения авторского –аудио и –видео контента.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.3 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Пользователь</span> – дееспособное физическое лицо, достигшее 18 лет, загрузившее Hitfly и создавшее учётную, прошедшее авторизацию, давшее согласие на обработку персональных данных Администрации.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.4 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Плагиат</span> — умышленно совершаемое физическим лицом незаконное использование или распоряжение охраняемыми результатами чужого творческого труда, которое сопровождается доведением до других лиц ложных сведений о себе как о действительном авторе.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.5 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Спам</span> — массовая рассылка корреспонденции лицам, не выражавшим желания её получать.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.6 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Регистрация</span> – создание учетной записи, при помощи которой Пользователь сможет получить доступ к сервисам Hitfly.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;1.7 </span><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">Аккаунт</span> – учетная запись, совокупность данных о Пользователе, необходимая для его аутентификации и предоставления доступа к личным данным и настройкам.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">2. </span>Права и обязанности Пользователей</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.1 </span>Пользователь обязуется использовать Приложение исключительно в целях личного, некоммерческого использования, не нарушая права и законные интересы Администрации, иных Пользователей, третьих лиц, предусмотренные настоящим Соглашением и законодательством РФ.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.2 </span>Если Пользователем не доказано обратное, любые действия, совершенные с использованием его мобильного устройства, считаются совершенными соответствующим Пользователем.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.3 </span>Пользователь самостоятельно несет ответственность за использование Hitfly и его сервисов любыми способами, прямо не предусмотренными Соглашением.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.4 </span>Пользователь не вправе регистрировать два и более Аккаунта для использования Приложения. При выявлении наличия двух и более Аккаунтов, принадлежащих одному Пользователю, Администрация оставляет за собой право заблокировать все Аккаунты.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.5 </span>При использовании Hitfly Пользователь не вправе:
                        <span style="display: block; margin-top: 1em; margin-right: 0; margin-bottom: 1em; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0; padding-left: 40px;">
                            <span style="display: block;">- размещать и/или распространять контент, который является незаконным, вредоносным, клеветническим, оскорбительным, демонстрирует и/или пропагандирует насилие, содержит элементы порнографии (в том числе детской);</span>
                            <span style="display: block;">- нарушать интеллектуальные права третьих лиц, в том числе несовершеннолетних;</span>
                            <span style="display: block;">- размещать и/или распространять не разрешенную специальным образом рекламную информацию, спам или использовать Hitfly для перенаправления пользователей на страницы других ресурсов;</span>
                            <span style="display: block;">- несанкционированно собирать и хранить персональные данные других Пользователей;</span>
                            <span style="display: block;">- любым способом вмешиваться в работу электронной площадки;</span>
                            <span style="display: block;">- побуждать к совершению противоправных действий, а также содействовать лицам, действия которых направлены на нарушение ограничений и запретов, указанных в действующем законодательстве Российской Федерации и настоящем Соглашении;</span>
                            <span style="display: block;">- другим образом нарушать нормы законодательства, в том числе нормы международного права.</span>
                        </span>
                    </span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;2.6 </span>Пользователь имеет право в любое время в одностороннем внесудебном порядке отказаться от исполнения Соглашения путем удаления Приложения со своего мобильного устройства.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">3. </span>Регистрация и правила пользования приложением Hitfly</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3.1 </span>Для использования Hitfly, Пользователю необходимо пройти процедуру регистрации, в результате которой для Пользователя будет создана уникальная учетная запись (Аккаунт).</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3.2 </span>Для регистрации Пользователь обязуется достоверно и полно заполнить информацию о себе по вопросам, предлагаемым в регистрационной Форме, и поддерживать эту информацию в актуальном состоянии. Пользователь несет полную ответственность за точность, полноту и достоверность предоставленной при регистрации информации.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3.3 </span>Пользователь подтверждает и гарантирует, что все действия, предусмотренные для него настоящим Соглашением, совершаются лицом, чьи данные направлены при создании Аккаунта. Администрация оставляет за собой право в любой момент потребовать от Пользователя подтверждения данных, указанных при регистрации, и/или запросить предоставить документы, удостоверяющие личность. Непредставление таких документов будет расцениваться Администрацией, как нарушение Соглашения, и может повлечь блокировку Аккаунта Пользователя.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3.4 </span>После прохождения процедуры регистрации Пользователь получает уникальную пару логин/пароль, предоставляющую доступ к Hitfly. Пользователь обязуется ни при каких обстоятельствах не сообщать логин/пароль третьим лицам и несет полную ответственность за действия, совершенные с использованием его логина и/или пароля.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;3.5 </span>Пользователь имеет право подать жалобу на информацию, содержащуюся в сообщениях, в адрес Администрации («спам», «плагиат», «оскорбление», «нецензурная брань»); ответственность за неправомерность жалобы возложена на Пользователя. Администрация оставляет за собой право оставить жалобу Пользователя без рассмотрения без объяснения причин.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">4. </span>Права и обязанности Администрации</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.1 </span>Мобильное приложение «Hitfly» предоставляется на условиях «как есть». Администрация обязуется приложить необходимые усилия по недопущению сбоев в работе Hitfly, но не несет ответственности за временные и перерывы в работе мобильного приложения, вне зависимости от причин таких сбоев и их продолжительности.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.2 </span>Администрация вправе осуществлять обработку персональных данных Пользователей и передавать их третьим лицам в целях исполнения настоящего Соглашения и разрешения претензий, связанных с исполнением настоящего Соглашения без дополнительного согласия Пользователя.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.3 </span>В случае, если Администрацией будет обнаружено недобросовестное использование Пользователем Hitfly, Администрация имеет право в любой момент заблокировать аккаунт такого Пользователя в Hitfly без уведомления Пользователя.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.4 </span>Администрация вправе направлять Пользователю любым способом информацию о работе Hitfly, в том числе размещать рекламные сообщения на адрес электронной почты или номер телефона, указанный Пользователем.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.5 </span>Администрация не несет никакой ответственности за содержание сторонних ресурсов, ссылки на которые размещены в Hitfly.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;4.6 </span>Администрация не несет ответственности за комментарии, точки зрения, замечания и любые другие высказывания Пользователей Hitfly, отраженные в Сообщениях.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">5. </span>Дополнительные услуги</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.1 </span>Администрация вправе оказывать Пользователям как бесплатные, так и платные услуги. Об условиях предоставления платных услуг Администрация информирует Пользователей путем размещения в Hitfly следующей информации об услуге: наименование услуги, ее стоимость, форма и порядок оплаты.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.2 </span>Получение платных услуг осуществляется за внутреннее средство платежей Hitfly – баллы, которые возможно приобрести за реальную валюту или при совершении определенных активных действий в приложении.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.3 </span>При приобретении Пользователем баллов путем внесения реальных денежных средств, Пользователь соглашается с тем, что денежные средства не подлежат обратному обмену и возврату Пользователю, что не может расцениваться в качестве убытков Пользователя или неосновательного обогащения Администрации, в том числе в случае блокировки аккаунта Пользователя (добровольной или по инициативе Администрации из-за нарушения Пользователем условий настоящего Соглашения или законодательства).</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.4 </span>При приобретении баллов Пользователь обязуется использовать только те банковские карты и счета, которые принадлежат ему лично или доступ, к которым был получен им на законных основаниях. Администрация ни коим образом не осуществляет кредитование Пользователей, а также не предоставляет рассрочку.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.5 </span>При приобретении Пользователем баллов, он обязуется следовать предложенным инструкциям, касающимся оплаты. Администрация не несет ответственность за правильность исполнения Пользователем указанных инструкций. Также Администрация не несет ответственность и не обязано компенсировать Пользователю денежные средства, в случае, если Пользователь осуществили оплату дополнительных услуг с нарушением правил, установленных использованными им платежными системами.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;5.6 </span>Пользователь самостоятельно несет все расходы, связанные с перечислением денежных средств, включая возможные сборы и комиссии.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">6. </span>Передача прав</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.1 </span>Весь размещенные в Hitfly контент является объектом исключительного права Пользователей, которые его разместили. Автор гарантирует, что является автором размещенного контента.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.2 </span>Пользователи передают Администрации и Hitfly права на хранение, копирование, распространение и воспроизведение (доведение до общего сведения) контента без цели извлечения прибыли (неисключительная лицензия).</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.3 </span>После размещения контента Пользователем у Администрации не возникает обязательства по выплате Пользователю авторского вознаграждения (роялти), или каких-либо иных сумм.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.4 </span>Пользователи передают Администрации и Hitfly право на показ имени (и иных данных Аккаунта) в строке, отображающей действия Пользователя.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.5 </span>Пользователи предоставляют всем иным Пользователям неисключительное право на использование своего контента путем просмотра и воспроизведения, а также иные права исключительно с целью личного некоммерческого использования.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;6.6 </span>Размещение контента в приложении Hitfly никаким образом не ограничивает права Пользователей для публикации их на других ресурсах, либо любого иного, предусмотренного действующим законодательством Российской Федерации, использования контента.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">7. </span>Политика конфиденциальности</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.1 </span>В соответствии с положением Федерального закона от 27.07.2006 №152 ФЗ «О персональных данных» Пользователи свободно, своей волей и в своем интересе предоставляют Администрации свои персональные данные в следующем составе:
                        имя, номер телефона, адрес электронной почты, данные о модели мобильного устройства Пользователя (производитель, модель, версия операционной системы, идентификатор устройств и иные технические параметры и идентификаторы, включая IMEI), и иная информация, которую Пользователь может указать.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.2 </span>Пользователи дают согласие на совершение следующих действий со своими персональными данными:
                        сбор (получение), запись, систематизация, хранение, уточнение, извлечение, использование, передача (предоставление, доступ), блокирование, обезличивание, удаление и уничтожение персональных данных; действия (операции), совершаемые с использованием средств автоматизации.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.3 </span>Указанное согласие на обработку персональных данных начинает действовать с момента принятия Пользователями условий Соглашения.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.4 </span>Администрация не собирает информацию, которую применимое законодательство запрещает собирать, и не использует для сбора информации способы, запрещенные указанным законодательством.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.5 </span>Администрация не несёт ответственности за получение третьими лицами персональных данных Пользователей путём получения доступа к мобильному устройству Пользователей.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.6 </span>В случае реорганизации Администрации персональные данные Пользователей и иная информация, полученная с использованием Hitfly, будут переданы правопреемнику. Аналогичным образом указанная информация может быть передана третьему лицу в случае переуступки прав на Hitfly. Об указанных фактах Администрация обязуется заблаговременно уведомить Пользователей.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.7 </span>Пользователи вправе в любое время обратиться к Администрации с требованием о предоставлении информации о том какие данные обрабатываются в программно-аппаратных комплексах Hitfly. Требование о прекращении обработки данных может быть направлено только после удаления Аккаунта.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.8 </span>Администрация обязуется предоставить Пользователю запрошенную информацию и/или прекратить обработку данных в течение 30 дней со дня поступления соответствующего запроса.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;7.9 </span>Администрация оставляет за собой право передать персональные данные Пользователей в правоохранительные органы в порядке, определенном законодательством, в случае, если станет достоверно известно о совершении Пользователем деяния, за которое установлено уголовное, административное или иное наказание.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">8. </span>Ответственность</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.1 </span>Пользователи Hitfly несут личную ответственность за любую информацию, размещенную от имени своего Аккаунта, а также сообщенную другим Пользователям и любые взаимодействия с другими Пользователями.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.2 </span>В случае возникновения споров и разногласий, таковые будут рассмотрены и разрешены Сторонами в порядке переговоров и/или обмена письменными сообщениями. Срок рассмотрения претензий 30 календарных дней с даты получения.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.3 </span>Стороны обязуются прилагать все возможные усилия, направленные на разрешение спорных вопросов в досудебном порядке.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.4 </span>В случае невозможности разрешения спора в претензионном порядке, Соглашения, спор будет рассмотрен в суде по месту нахождения Ответчика.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.5 </span>Стороны признают в качестве письменных доказательств электронную переписку между собой и/или с использованием возможностей Hitfly.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.6 </span>При любых обстоятельствах ответственность Hitfly в соответствии со статьей 15 Гражданского кодекса Российской Федерации ограничена общей суммой в размере 5 000 (пять тысяч) рублей.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;8.7 </span>Споры, возникающие между другими Пользователями в процессе использования Hitfly, не рассматриваются Администрацией.</span>
                </span>
            </span>
            <span style="display: block;">
                <h2 style="text-align: left; margin-bottom: 20px; margin-left: 15px;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">9. </span>Заключительные положения</h2>
                <span style="padding-left: 0; margin-bottom: 36px; display: block; margin-top: 1em; margin-right: 0; margin-left: 15px; padding-top: 0; padding-right: 0; padding-bottom: 0;">
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;9.1 </span>В случае если любые положения Соглашения окажутся не подлежащими применению, такие положения будут применяться в возможных пределах, наиболее соответствующим намерениям Сторон, а остальные положения Соглашения сохранят свою силу.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;9.2 </span>Пользователи самостоятельно определяют условия и порядок использования созданного аккаунта, которые, однако, не могут противоречить настоящему Соглашению.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;9.3 </span>Пользователь соглашается получать от Администрации на указанный в его Аккаунте электронный адрес информационные электронные сообщения, в том числе рекламного характера.</span>
                    <span style="display: block;"><span style="font-family: &quot;Gotham Pro Bold&quot; , serif; font-weight: 900;">&emsp;9.4 </span>Настоящее Соглашение составлено на русском языке. Действующая редакция Соглашения опубликована по адресу: www.myhitlfy.ru.</span>
                </span>
            </span>
        </span>
    </div>
</div>
@endsection
