# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

## Запрос списков жанров
GET http://127.0.0.1:9090/api/v1/genre
Accept: application/json

###

## Запрос одного жанра
GET http://127.0.0.1:9090/api/v1/genre/64
Accept: application/json

###
