# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

## Запрос списков жанров
GET http://127.0.0.1:9090/api/v1/genre
Accept: application/json

###

## Запрос одного жанра
GET http://127.0.0.1:9090/api/v1/genre/64
Accept: application/json

###

## Запрос списков групп
GET http://127.0.0.1:9090/api/v1/music_group
Accept: application/json

###

## Запрос одной группы
GET http://127.0.0.1:9090/api/v1/music_group/82
Accept: application/json

###


POST http://127.0.0.1:9090/register
Content-Type: application/json

{
  "username": "test",
  "password": "content",
  "email": "test@mail.ru"

}

###


POST http://127.0.0.1:9090/graphql
Content-Type: application/json

{
  "operationName":null,
  "variables":{},
  "query":"{tracks(count: 1, page: 3) {paginatorInfo {count total firstItem } data { id track_name song_text genre { name created_at image created_at } user { username email } album { title author } } } } "}

###
