version: '3'
services:
    nginx:
        container_name: hitfly_nginx
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        ports:
            - 9090:80
            - 9091:8080
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www/html
        depends_on:
            - php
            - maria
            - node
        command: [nginx-debug, '-g', 'daemon off;']
    maria:
        container_name: hitfly_db
        restart: always
        volumes:
            - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
            - ./docker/dbdata/:/var/lib/mysql
        ports:
            - '53306:3306'
        build:
            context: docker/mariadb
            dockerfile: Dockerfile
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_DATABASE}
    php:
        container_name: hitfly_php
        build:
            context: docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
        ports:
            - 2346:2346
        links:
            - maria:hitfly_db
    redis_host:
        container_name: hitfly_redis
        build:
            context: ./docker/redis
            dockerfile: Dockerfile
        ports:
            - 6379:6379
        volumes:
            - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    es01:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
      container_name: es01
      environment:
        - node.name=es01
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
        - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - 9200:9200
    node:
        #    do not specify any env variables for the server cause it is already configured
        container_name: hitfly_node
        image: node:10.16.3-jessie
        user: "node"
        working_dir: /home/node/app
        volumes:
            - ./ssr:/home/node/app
        command: "npm run container:server:run:watch"
        expose:
          - 3030
