version: '3.2'
services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - '9090:80'
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './:/var/www/html'
      - './storage/logs/nginx:/var/log/nginx'
    depends_on:
      - php
      - maria
    env_file:
      - docker_server.env
    command: [nginx-debug, '-g', 'daemon off;']
  maria:
    container_name: maria_db
    restart: always
    volumes:
      - './docker/mariadb/my.cnf:/etc/mysql/my.cnf'
      - './docker/dbdata/:/var/lib/mysql'
    ports:
      - '53306:3306'
    build:
      context: docker/mariadb
      dockerfile: Dockerfile
    env_file:
      - docker_server.env
  php:
    container_name: php_docker
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - './:/var/www/html'
      - './docker/php/config/php.ini:/usr/local/etc/php/php.ini'
    ports:
      - "2346:2346"
    links:
      - "maria:maria"
    env_file:
      - docker_server.env
  redis_host:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'
  node:
#    do not specify any env variables for the server cause it is already configured
    image: node:10.16.3-jessie
    user: "node"
    working_dir: /home/node/app
    ports:
      - '3031:3030'
    volumes:
      - ./ssr:/home/node/app
    command: "npm run container:server:run:watch"
