<?php

namespace App\BuisnessLogic;

class TopFifty
{
    const TOP_FIFTY_KEY = 'TOP_FIFTY_KEY';
    const TOP_FIFTY_KEY_CALCULATED = 'TOP_FIFTY_KEY_CALCULATED';
    const LISTENED_TRACK_KEY = 'LISTENED_TRACK_KEY';
    const LISTENED_TRACK_KEY_CALCULATED = 'LISTENED_TRACK_KEY_CALCULATED';
    const LISTENED_USER_KEY = 'LISTENED_USER_KEY';
}
